CREATE DATABASE IF NOT EXISTS online_shop;

DROP TABLE IF EXISTS online_shop_user CASCADE;
CREATE TABLE online_shop_user (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	email_address VARCHAR(255) NOT NULL,
	password CHAR(20) NOT NULL,
	online_shop_user_role_id bigint NOT NULL,
	online_shop_cart_id bigint NOT NULL,
	online_shop_address_id bigint,
	registration_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT online_shop_user_pk PRIMARY KEY (id)
);

DROP TABLE IF EXISTS online_shop_user_address CASCADE;
CREATE TABLE online_shop_user_address (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	city VARCHAR(255) NOT NULL,
	postal_code int NOT NULL,
	street_name VARCHAR(255) NOT NULL,
	street_number VARCHAR(255) NOT NULL,
	apartment_number VARCHAR(255),
	CONSTRAINT online_shop_address_pk PRIMARY KEY (id)
);

DROP TABLE IF EXISTS online_shop_cart CASCADE;
CREATE TABLE online_shop_cart (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	online_shop_product_id bigint,
	CONSTRAINT online_shop_cart_pk PRIMARY KEY (id)
);

DROP TABLE IF EXISTS online_shop_product CASCADE;
CREATE TABLE online_shop_product (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	product_name VARCHAR(255) NOT NULL,
	product_price DECIMAL(100, 2) NOT NULL,
	product_type_id bigint NOT NULL,
	product_description VARCHAR(255),
	product_amount int NOT NULL,
	product_availability BOOLEAN,
	CONSTRAINT online_shop_product_pk PRIMARY KEY (id)
);

DROP TABLE IF EXISTS online_shop_inventory CASCADE;
CREATE TABLE online_shop_inventory (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	online_shop_product_id bigint,
	CONSTRAINT online_shop_inventory_pk PRIMARY KEY (id)
);

DROP TABLE IF EXISTS online_shop_product_type CASCADE;
CREATE TABLE online_shop_product_type (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	product_type VARCHAR(255) NOT NULL,
	CONSTRAINT online_shop_product_type_pk PRIMARY KEY (id)
);

DROP TABLE IF EXISTS online_shop_user_role_type CASCADE;
CREATE TABLE online_shop_user_role_type (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	online_shop_user_role VARCHAR(255) NOT NULL,
	CONSTRAINT online_shop_user_role_type_pk PRIMARY KEY (id)
);

ALTER TABLE online_shop_user ADD CONSTRAINT online_shop_user_address
	FOREIGN KEY (online_shop_address_id)
	REFERENCES online_shop_user_address (id);
	
ALTER TABLE online_shop_user ADD CONSTRAINT online_shop_user_cart
	FOREIGN KEY (online_shop_cart_id)
	REFERENCES online_shop_cart (id);
	
ALTER TABLE online_shop_user ADD CONSTRAINT online_shop_user_role_type
	FOREIGN KEY (online_shop_user_role_id)
	REFERENCES online_shop_user_role_type (id);
		
ALTER TABLE online_shop_product ADD CONSTRAINT online_shop_product_type
	FOREIGN KEY (product_type_id)
	REFERENCES online_shop_product_type (id);
	
ALTER TABLE online_shop_cart ADD CONSTRAINT online_shop_cart_product
	FOREIGN KEY (online_shop_product_id)
	REFERENCES online_shop_product (id);

ALTER TABLE online_shop_inventory ADD CONSTRAINT online_shop_inventory_product
	FOREIGN KEY (online_shop_product_id)
	REFERENCES online_shop_product (id);

//WITHOUT HIBERNATE(JDBC), LOAD ALL SQL FILE INTO POSTGRESQL.:
	INSERT INTO online_shop_user_role_type VALUES (1, 'MEMBER');
	INSERT INTO online_shop_product_type VALUES(1, 'OTHER');
	INSERT INTO online_shop_product VALUES (1, 'TEST PRODUCT', 330, 1, '', 3, TRUE);
	INSERT INTO online_shop_cart VALUES (1, 1);
	INSERT INTO online_shop_user_address VALUES (1, 'CITY', 1111, 'STREET NAME', 'STREET_NUMBER', '');
	INSERT INTO online_shop_user VALUES (1, 'FIRST NAME', 'LAST NAME', 'test@test.com', 'password', 1, 1, 1);
	INSERT INTO online_shop_inventory VALUES (1, 1);

//WITH HIBERNATE(JPA):
	INSERT INTO online_shop_user_role_type VALUES (1, 'MEMBER');
	INSERT INTO online_shop_product_type VALUES(1, 'OTHER');
	INSERT INTO online_shop_cart VALUES (1);
	INSERT INTO online_shop_inventory VALUES (1);
	INSERT INTO online_shop_product VALUES (3, TRUE, 333, 1, 1, 1, 1, '', 'TEST PRODUCT');
	INSERT INTO online_shop_user_address VALUES (1111, 1, '', 'CITY', 'STREET NAME', 'STREET NUMBER');
	INSERT INTO online_shop_user VALUES (1, 1, 1, 1, current_timestamp, 'test@test.com', 'FIRST NAME', 'LAST NAME', 'password');